GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/user-api/users/kiran

###
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
   "username":"kiran",
   "password":"kiran",
   "email":"kiran@mail.com",
   "city":"hyderabad"
}

###
POST http://localhost:4000/user-api/user-login
Content-Type: application/json

{
   "username":"kiran",
   "password":"kiran"
  
}



###
PUT http://localhost:4000/user-api/user/kiran
Content-Type: application/json

{
    "username":"kiran",
   "password":"kiran",
   "email":"kiranbabu@mail.com"
}

###
DELETE http://localhost:4000/user-api/user/kiran

###
GET http://localhost:4000/user-api/restore-user/kiran


###
GET http://localhost:4000/user-api/protected-route
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmFuIiwiaWF0IjoxNjg2NjY3NTA2LCJleHAiOjE2ODY2Njc1MjF9.KchukupBmQuwpzcP7NElIYBzpeNadM7qPAywcE5Queo



###PRODUCT ROUTES
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
    "productId":200,
    "productName":"tv",
    "price":300000,
    "brand":"sony"
}

###


###
GET http://localhost:4000/product-api/products/200

###
GET http://localhost:4000/product-api/products
