GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/user-api/users/300

###
POST http://localhost:4000/user-api/user
Content-Type: application/json

{
    "id":200,
    "username":"bhanu",
    "email":"bhanu@mail.com"
}




###
PUT http://localhost:4000/user-api/user/200
Content-Type: application/json

{
    "id":200,
    "username":"bhanukumar",
    "email":"bhanukumar@mail.com"
}

###
DELETE http://localhost:4000/user-api/user/200

###
get http://localhost:4000/product-api/product